name: BaseFFA
version: 2.2.2-SNAPSHOT
author: Sorridi
main: net.herospvp.base.Base
load: POSTWORLD
depend:
  - PlaceholderAPI
  - Vault
  - ActionBarAPI
commands:
  forcesave:
    permission: base.*
  spawn:
  notifiche:
    aliases: [not]
  reply:
    aliases: [r]
  message:
    aliases: [m, w, msg, write]