name: BaseFFA
version: ${project.version}
author: Sorridi
main: net.herospvp.base.Base
depend:
  - heros-core
  - PlaceholderAPI
  - Vault
  - ActionBarAPI
commands:
  forcesave:
    permission: base.*
  spawn:
  notifiche:
    aliases: [not]
  reply:
    aliases: [r]
  message:
    aliases: [m, w, msg, write]